// Committed, static golden fixture — hand-authored to match P2's real
// ProductionPackageHandoff contract (pipeline2_creative/src/types.ts)
// field-for-field, including the AssetRequirement.shot_id FK verified
// present in P2's frozen source. Not generated by importing or running
// pipeline2_creative — P3 has no dependency edge on P2.

import type { ProductionPackageHandoffInput } from "../../src/types.js";
import { sha256 } from "../../src/ids.js";

// TIER-1 REPAIR NOTE (T1.2): this fixture used to declare fixed placeholder
// hashes (HASH_A/HASH_B). That was only viable while P3 accepted any
// well-formed-looking hash without recomputing it. Now that the P2 -> P3
// boundary performs REAL verification (ingest.ts::verifyProductionPackageIntegrity),
// a golden fixture must be genuinely SEALED. The manifest/integrity block is
// computed here from the fixture's own content, mirroring P2's
// manifest.ts::buildManifestAndIntegrity canonicalization exactly.
const P2_SECTION_PURPOSE: Record<string, string> = {
  scenes: "P2.08 canonical Scene plan",
  shots: "P2.08 canonical Shot plan",
  asset_requirements: "P2.07 canonical Asset Requirement plan",
  prompts: "P2.09 rendered Google Flow prompts",
  decision_log: "P2.06 AI Director decision log",
  voice_script: "P2.10 narration script",
  pronunciation_flags: "P2.10 pronunciation/number risk flags",
  voice_lines: "P2.10 claim/line voice lineage (T2.4)",
};

function canonicalize(value: unknown): string {
  return JSON.stringify(value, (_key, val) => {
    if (val && typeof val === "object" && !Array.isArray(val)) {
      return Object.fromEntries(Object.entries(val).sort(([a], [b]) => a.localeCompare(b)));
    }
    return val;
  });
}

/** Seals a fixture package the same way P2 seals a real one. */
export function sealProductionPackage<T extends Record<string, unknown>>(pkg: T): T {
  const manifest: Array<{ path: string; sha256: string; purpose: string }> = [];
  const per_file: Record<string, string> = {};
  for (const key of Object.keys(P2_SECTION_PURPOSE)) {
    const path = `production_package/${key}.json`;
    const hash = sha256(canonicalize(pkg[key] ?? []));
    manifest.push({ path, sha256: hash, purpose: P2_SECTION_PURPOSE[key]! });
    per_file[path] = hash;
  }
  manifest.sort((a, b) => a.path.localeCompare(b.path));
  const package_sha256 = sha256(manifest.map((m) => `${m.path}:${m.sha256}`).join("|"));
  return { ...pkg, manifest, integrity_hashes: { package_sha256, per_file } };
}

const UNSEALED_PRODUCTION_PACKAGE_FIXTURE = {
  package_id: "ppkg_fixture0001aaaa",
  production_package_version: "1.0.0",
  project_id: "proj_fixture0001aaaa",
  research_package_ref: "rpkg_fixture0001aaaa",
  scenes: [
    {
      scene_id: "scene_aqueduct_intro",
      purpose: "establish the aqueduct system",
      shots: ["shot_wide_arch", "shot_water_flow"],
      continuity_requirements: ["stone color consistent across shots"],
      narrative_function: "opening",
    },
  ],
  shots: [
    {
      shot_id: "shot_wide_arch",
      scene_id: "scene_aqueduct_intro",
      purpose: "wide establishing shot of the aqueduct arches",
      duration_intention: "3-4s",
      camera: { angle: "low", movement: "static", lens: "wide", framing: "wide" },
      action: "camera holds on the aqueduct arches against the sky",
      continuity_anchors: ["stone_color"],
      reference_requirements: [],
      asset_type: "VISUAL_IMAGE",
      generation_method: "google_flow",
    },
    {
      shot_id: "shot_water_flow",
      scene_id: "scene_aqueduct_intro",
      purpose: "close-up on flowing water in the channel",
      duration_intention: "2-3s",
      camera: { angle: "eye-level", movement: "slow push-in", lens: "macro", framing: "close_up" },
      action: "water flows steadily through the stone channel",
      continuity_anchors: ["stone_color"],
      reference_requirements: [],
      asset_type: "VISUAL_VIDEO",
      generation_method: "google_flow",
    },
  ],
  asset_requirements: [
    {
      asset_requirement_id: "astreq_wide_arch",
      shot_id: "shot_wide_arch",
      expected_media_type: "VISUAL_IMAGE",
      // AUDIT FIX: matches P2's REAL default output — P2's
      // runP207AssetPlanning leaves this {} unless the caller supplies
      // per-shot properties, which its own golden example never does.
      // Compatibility is now checked via expected_media_type instead.
      expected_media_properties: {},
      generation_method: "google_flow",
      reference_lineage: [],
      required: true,
    },
    {
      asset_requirement_id: "astreq_water_flow",
      shot_id: "shot_water_flow",
      expected_media_type: "VISUAL_VIDEO",
      expected_media_properties: {},
      generation_method: "google_flow",
      reference_lineage: [],
      required: true,
    },
  ],
  prompts: [
    {
      spec: {
        prompt_spec_id: "pspec_wide_arch",
        prompt_family: "flow.shot.wide",
        subject: "A Roman stone aqueduct with multiple tall arches",
        composition: "low angle, arches filling the frame",
        style: "documentary realism, natural daylight",
        negative_constraints: ["no modern objects"],
        axis_tags: ["wide", "static"],
        traceable_to: { shot_id: "shot_wide_arch", decision_id: "dec_camera_choice" },
      },
      rendered: {
        provider: "google_flow",
        prompt_text: "Subject: A Roman stone aqueduct with multiple tall arches\nComposition: low angle, arches filling the frame",
        rendered_at: "2026-08-24T00:10:00.000Z",
      },
    },
    {
      spec: {
        prompt_spec_id: "pspec_water_flow",
        prompt_family: "flow.shot.closeup",
        subject: "Clear water flowing through a carved stone channel",
        composition: "close-up, water filling most of the frame",
        style: "documentary realism, natural daylight",
        negative_constraints: [],
        axis_tags: ["close_up", "push_in"],
        traceable_to: { shot_id: "shot_water_flow", decision_id: "dec_camera_choice" },
      },
      rendered: {
        provider: "google_flow",
        prompt_text: "Subject: Clear water flowing through a carved stone channel\nComposition: close-up, water filling most of the frame",
        rendered_at: "2026-08-24T00:10:00.000Z",
      },
    },
  ],
  decision_log: [
    {
      decision_id: "dec_camera_choice",
      status: "approved",
      question: "camera_choice",
      recommendation: "static",
      approving_actor: "user:mk350174",
    },
  ],
  voice_script:
    "The Aqua Appia, Rome's first aqueduct, was completed in 312 BC.\n\nWater flowed steadily through the stone channel by gravity alone.",
  pronunciation_flags: [
    { claim_id: "claim_facts_aquaappia", token: "312 BC", flag_type: "date", note: "Date-like token; verify pronunciation." },
  ],
  user_approval_state: [
    {
      gate_id: "A2",
      state_before: "REFERENCES_PROPOSED",
      approval_record_id: "appr_fixture_refs",
      actor: "user:mk350174",
      timestamp: "2026-08-24T00:05:00.000Z",
      object_version_being_approved: "ref_ancientengineering",
      state_after: "REFERENCES_APPROVED",
      downstream_operation_unlocked: "P2.02 Content Understanding",
    },
    {
      gate_id: "A2",
      state_before: "ART_DIRECTION_DRAFTED",
      approval_record_id: "appr_fixture_art",
      actor: "user:mk350174",
      timestamp: "2026-08-24T00:06:00.000Z",
      object_version_being_approved: "art_aqueducts",
      state_after: "ART_DIRECTION_APPROVED",
      downstream_operation_unlocked: "P2.07/P2.08",
    },
    {
      gate_id: "A3",
      state_before: "PRODUCTION_PACKAGE_DRAFTED",
      approval_record_id: "appr_fixture_package",
      actor: "user:mk350174",
      timestamp: "2026-08-24T00:07:00.000Z",
      object_version_being_approved: "ppkg_fixture0001aaaa",
      state_after: "PRODUCTION_PACKAGE_APPROVED",
      downstream_operation_unlocked: "Manual Google Flow stage; Pipeline 3 may consume this Production Package once assets are delivered",
    },
  ],
  manifest: [] as Array<{ path: string; sha256: string; purpose: string }>,
  integrity_hashes: { package_sha256: "", per_file: {} as Record<string, string> },
};

export const PRODUCTION_PACKAGE_FIXTURE: ProductionPackageHandoffInput = sealProductionPackage(
  UNSEALED_PRODUCTION_PACKAGE_FIXTURE as unknown as Record<string, unknown>,
) as unknown as ProductionPackageHandoffInput;
