// Committed, static golden fixture — hand-authored to match P1's documented
// ResearchPackageHandoff contract (pipeline1_research/src/types.ts)
// field-for-field. Not generated by importing or running pipeline1_research
// — P2 has no dependency edge on P1 (see plan "Package layout"). This is
// how the P1 -> P2 handoff compatibility is verified: a realistic package
// shaped exactly like P1's real golden-example output.

import type { ResearchPackageHandoffInput } from "../../src/types.js";
import { sha256 } from "../../src/ids.js";

// TIER-1 REPAIR NOTE (T1.2): the manifest/integrity block below used to be
// hand-written placeholder strings ("aaa", "bbb",
// "fixture0packagehash000..."). That was only viable while P2 accepted any
// well-formed-looking hash without recomputing it. Now that the P1 -> P2
// boundary performs REAL verification, a golden fixture must be a genuinely
// SEALED package — so the manifest and hashes are computed here from the
// fixture's own content, using the identical canonical representation P1
// uses (pipeline1_research/src/manifest.ts). The fixture stays
// hand-authored and dependency-free; only the seal is now real.
const P1_SECTION_PURPOSE: Record<string, string> = {
  research_scope: "P1.02 frozen, human-approved research scope",
  sources: "P1.03 acquired sources",
  evidence: "P1.03 extracted evidence",
  claims: "P1.03/P1.04 claims with dimension assignment",
  verifications: "P1.04 verification verdicts",
  knowledge_package: "P1.05/P1.06 synthesized knowledge structure",
  unresolved_questions: "P1.06 explicit open/unresolved questions",
  handoff_notes: "P1.07 machine-readable notes for P2",
};

function canonicalize(value: unknown): string {
  return JSON.stringify(value, (_key, val) => {
    if (val && typeof val === "object" && !Array.isArray(val)) {
      return Object.fromEntries(Object.entries(val).sort(([a], [b]) => a.localeCompare(b)));
    }
    return val;
  });
}

/** Seals a fixture package the same way P1 seals a real one. */
export function sealResearchPackage<T extends Record<string, unknown>>(pkg: T): T {
  const manifest: Array<{ path: string; sha256: string; purpose: string }> = [];
  const per_file: Record<string, string> = {};
  for (const key of Object.keys(P1_SECTION_PURPOSE)) {
    const path = `handoff/${key}.json`;
    const hash = sha256(canonicalize(pkg[key]));
    manifest.push({ path, sha256: hash, purpose: P1_SECTION_PURPOSE[key]! });
    per_file[path] = hash;
  }
  manifest.sort((a, b) => a.path.localeCompare(b.path));
  const package_sha256 = sha256(manifest.map((m) => `${m.path}:${m.sha256}`).join("|"));
  return { ...pkg, manifest, integrity_hashes: { package_sha256, per_file } };
}

const UNSEALED_FIXTURE = {
  package_id: "rpkg_fixture0001aaaa",
  schema_version: "1.0.0",
  project_id: "proj_fixture0001aaaa",
  manifest: [] as Array<{ path: string; sha256: string; purpose: string }>,
  integrity_hashes: { package_sha256: "", per_file: {} as Record<string, string> },
  research_scope: {
    scope_id: "scope_fixture0001aaaa",
    project_id: "proj_fixture0001aaaa",
    topic: "The Roman Aqueducts",
    question: "How was Rome supplied with water in antiquity?",
    constraints: ["focus on engineering, not politics"],
    state: "SCOPE_APPROVED",
  },
  sources: [
    {
      source_id: "src_frontinus0001",
      origin: "https://example.org/frontinus-de-aquaeductu",
      source_type: "secondary",
      retrieved_at: "2026-08-24T00:00:00.000Z",
      access_method: "manual_entry",
    },
  ],
  evidence: [
    {
      evidence_id: "ev_aquaappia0001",
      source_id: "src_frontinus0001",
      excerpt_or_pointer: "Frontinus records the Aqua Appia's completion in 312 BC.",
      retrieved_at: "2026-08-24T00:00:00.000Z",
      extraction_method: "manual_entry",
    },
  ],
  claims: [
    {
      claim_id: "claim_facts_aquaappia",
      statement: "The Aqua Appia, Rome's first aqueduct, was completed in 312 BC.",
      evidence_refs: ["ev_aquaappia0001"],
      derived_from: "construction_history",
      contradiction_refs: [],
      dimension: "facts",
    },
    {
      claim_id: "claim_quant_length",
      statement: "Rome's aqueduct network eventually exceeded 400 km in total length.",
      evidence_refs: ["ev_aquaappia0001"],
      derived_from: "total_length",
      contradiction_refs: [],
      dimension: "quantitative",
    },
  ],
  verifications: [
    { verification_id: "verif_facts_aquaappia", claim_id: "claim_facts_aquaappia", status: "VERIFIED" },
    { verification_id: "verif_quant_length", claim_id: "claim_quant_length", status: "INFERRED" },
  ],
  knowledge_package: {
    verification_state_schema_version: "v1",
    facts: [
      {
        claim_id: "claim_facts_aquaappia",
        statement: "The Aqua Appia, Rome's first aqueduct, was completed in 312 BC.",
        evidence_refs: ["ev_aquaappia0001"],
        derived_from: "construction_history",
        contradiction_refs: [],
        dimension: "facts",
      },
    ],
    quantitative: [
      {
        claim_id: "claim_quant_length",
        statement: "Rome's aqueduct network eventually exceeded 400 km in total length.",
        evidence_refs: ["ev_aquaappia0001"],
        derived_from: "total_length",
        contradiction_refs: [],
        dimension: "quantitative",
      },
    ],
    unknowns: [],
    open_questions: [],
  },
  unresolved_questions: [],
  handoff_notes: "Golden-example fixture matching P1's documented handoff contract, for P2 ingestion testing.",
  gates: [
    {
      gate_id: "A1",
      state_before: "PACKAGE_DRAFTED",
      approval_record_id: "appr_fixture0001",
      actor: "user:mk350174",
      timestamp: "2026-08-24T00:05:00.000Z",
      object_version_being_approved: "rpkg_fixture0001aaaa",
      state_after: "PACKAGE_APPROVED",
      downstream_operation_unlocked: "Pipeline 2 may consume this Research Package",
    },
  ],
};

export const RESEARCH_PACKAGE_FIXTURE: ResearchPackageHandoffInput = sealResearchPackage(
  UNSEALED_FIXTURE as unknown as Record<string, unknown>,
) as unknown as ResearchPackageHandoffInput;
