import assert from 'node:assert/strict';
import { createCanonicalIdentity, parentReferenceFromIdentity, createArtifactBinding } from '../dist/b00/identity.js';
import { proposeItem, approveItem, canonicalizeItem } from '../dist/b00/governance.js';
import { createBranchState } from '../dist/b12/orchestration.js';

const modules=['B01','B02','B03','B04','B05','B06','B07','B08','B09','B10','B11'];
const dependencies={B01:[],B02:['B01'],B03:['B01'],B04:['B01','B02','B03'],B05:['B01','B03','B04'],B06:['B01','B03','B04'],B07:['B04','B06'],B08:['B01','B06','B07'],B09:['B08','B06'],B10:['B09'],B11:['B10']};
function approvalHistory(){const binding=createArtifactBinding({decision:'Use approved channel role'},'decision-channel-role','B01_DECISION','v1.0');const p=proposeItem({itemId:binding.object_id,history:[],authority:'analyst',timestamp:'2026-09-06T01:00:00Z'});const a=approveItem({itemId:binding.object_id,history:p.history,authority:'user@example.test',timestamp:'2026-09-06T01:01:00Z',artifact:binding,requireArtifactBinding:true});return canonicalizeItem({itemId:binding.object_id,history:a.history,authority:'user@example.test',timestamp:'2026-09-06T01:02:00Z',artifact:binding,requireArtifactBinding:true}).history;}
function makeState(module,identities,extras={}){const lower=module.toLowerCase(),created='2026-09-06T02:00:00Z';const base={version:'v1.0',created_at:created,updated_at:created,user_decision_authority:'user@example.test',audit_trail:[{version:'v1.0',changed_at:created,changed_by:'user@example.test',summary:`${module} canonical fixture`}],decisions_made:[],recommendations_considered:[],evidence_refs:[],provenance_refs:[],governance_events:{},decision_timestamp:created,cannot_be_modified_until_next_version:true,...extras};const parentReferences=dependencies[module].map(p=>parentReferenceFromIdentity(p,identities[p],'integration_fixture_parent'));const identity=createCanonicalIdentity({object_id:`${lower}:v1.0:fixture`,object_type:`${module}_CANONICAL_STATE`,version:'v1.0',artifact:base,parent_references:parentReferences,created_at:created});identities[module]=identity;return{...base,identity};}
const identities={}, states={};const hist=approvalHistory();states.b01=makeState('B01',identities,{conflicts:[{conflict_id:'fixture-conflict',description:'Two strategic inputs disagree',affected_items:['territory-a','territory-b'],severity:'medium'}],decisions_made:[{decision_id:'fixture-user-decision',description:'User selected the canonical channel role',timestamp:'2026-09-06T01:01:00Z',user_authority:'user@example.test',rationale:'Explicit test decision'}],governance_events:{'decision-channel-role':hist},provenance_refs:[hist.at(-1).provenance]});
states.b02=makeState('B02',identities);states.b03=makeState('B03',identities,{evidence_refs:[{id:'fixture-uncertain-audience',source:'user_input:audience_claim',status:'UNKNOWN',origin:'USER_ASSERTION',basis:'ASSERTED',source_mode:'UNKNOWN'}]});states.b04=makeState('B04',identities);states.b05=makeState('B05',identities);states.b06=makeState('B06',identities);states.b07=makeState('B07',identities);states.b08=makeState('B08',identities,{analytics_results:[{result_id:'fixture-real-result',metric_id:'views',value:42,unit:'count',period_start:'2026-09-01',period_end:'2026-09-02',state:'VALIDATED',source_mode:'REAL',evidence_refs:[{id:'fixture-provider-evidence',source:'provider:test-fixture',status:'VERIFIED',origin:'PROVIDER_DATA',basis:'OBSERVED',source_mode:'REAL',production_eligible:true}]}],evidence_refs:[{id:'fixture-provider-evidence',source:'provider:test-fixture',status:'VERIFIED',origin:'PROVIDER_DATA',basis:'OBSERVED',source_mode:'REAL',production_eligible:true}]});states.b09=makeState('B09',identities,{recommendations_considered:[{recommendation_id:'fixture-rec',source_agent:'B09',proposal:'Investigate observed change',timestamp:'2026-09-06T02:00:00Z',adopted:false,rationale_if_rejected:'Insufficient causal evidence'}]});states.b10=makeState('B10',identities);states.b11=makeState('B11',identities,{compliance_checks:[{check_id:'fixture-unresolved-compliance',compliance_rule_id:'rule-1',subject:{subject_id:'subject-1',subject_type:'B10_PROPOSAL',subject_version:'v1.0',subject_content_hash:identities.B10.content_hash,affected_modules:['B10']},status:'UNKNOWN',check_basis:'NO_EVIDENCE',findings:['External compliance evidence not supplied'],finding_review_state:'UNREVIEWED',remediation_required:false,evidence_refs:[],provenance:{type:'INFERRED',decision_authority:'B11',timestamp:'2026-09-06T02:00:00Z',rationale:'No evidence means UNKNOWN'}}]});
const reader={};for(const m of Object.keys(states)){reader[m]={load:async(v)=>v==='v1.0'?states[m]:null,save:async()=>{},listVersions:async()=>['v1.0'],latest:async()=>states[m]};}
const branch=await createBranchState('v1.0','v1.0','v1.0','v1.0','v1.0','v1.0','v1.0','v1.0','v1.0','v1.0','v1.0',{upstreamReader:reader,now:()=> '2026-09-06T03:00:00Z'});
assert.equal(branch.module_versions.length,11);assert.equal(branch.module_versions.every(v=>v.identity_status==='VERIFIED'),true);assert.equal(branch.completeness_summary.structural_completeness,100);assert.equal(branch.completeness_summary.semantic_validity,'UNKNOWN');assert.equal(branch.completeness_summary.operational_readiness,'NOT_READY');assert.equal(branch.decisions_made.some(d=>d.decision_id==='fixture-user-decision'),true);assert.equal(branch.recommendations_considered.some(r=>r.recommendation_id==='fixture-rec'),true);assert.equal(branch.governance_events['decision-channel-role'].at(-1).state,'CANONICAL');assert.equal(states.b01.conflicts.length,1);assert.equal(branch.evidence_refs.some(e=>e.id==='fixture-uncertain-audience'&&e.status==='UNKNOWN'),true);
console.log(JSON.stringify({status:'PASS',module_versions:branch.module_versions.map(v=>({module:v.module,version:v.version,identity_status:v.identity_status,hash:v.content_hash.slice(0,12)})),structural_completeness:branch.completeness_summary.structural_completeness,semantic_validity:branch.completeness_summary.semantic_validity,operational_readiness:branch.completeness_summary.operational_readiness,decisions:branch.decisions_made.length,recommendations:branch.recommendations_considered.length,governance_subjects:Object.keys(branch.governance_events).length,semantic_findings:branch.completeness_summary.semantic_findings},null,2));
